[package]
name = "yew-scroll-area"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.7.0"
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = ["HtmlDivElement"] }
yew = "0.19.3"
yew-hooks = "0.1.56"
yew-style-in-rs = "0.3.2"
