[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = ["HtmlInputElement"] }
wee_alloc = "0.4.5"
yew = "0.19.3"
yew-style-in-rs = "0.3.2"

[dependencies.yew-scroll-area]
path = "../../yew-scroll-area"
